[build]
  publish = "."                       # root folder with index.html
  functions = "netlify/functions"     # path to serverless functions
  command = ""                        # no build command needed for static HTML


